### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by YesterMester** [Cattn/GBA2.0#1]
So I made an unblocked game website and I added this to it and when I launch any console thats not ds it gives me a network error. Any fixes?

**Comment by Cattn** [comment]
Please make sure you forked Cattn/gba-host and that this site is available at /gba and gba-host is available at /gba-host


Otherwise, visit Math-Study/gba-SERVER-READY

If you are hosting on root

**Comment by YesterMester** [comment]
I'm kinda new to website making and slow in the head could you explain this part a little better "and that this site is available at /gba and gba-host is available at /gba-host" if I fix it before you write back ill close the issue.

**Comment by YesterMester** [comment]
Thanks for the help I get it now.

**Comment by Cattn** [comment]
> Thanks for the help I get it now.

Great to hear! please lmk if you have any other questions

**Comment by YesterMester** [comment]
it seems to be having some trouble building the page.

**Comment by YesterMester** [comment]
Ive tried 5 times to re-run the checks and it fails everytime.

**Comment by Cattn** [comment]
> Ive tried 5 times to re-run the checks and it fails everytime.

can you send a link to the repo

**Comment by YesterMester** [comment]
I'm going to try it locallyhttps://github.com/YesterMester/emustuff-host

**Comment by Nailington** [comment]
Please rename the repo to `gba-host`

We have everything relatively linked assuming that name....

**Comment by Nailington** [comment]
Oh, and building has a HIGH chance of failing right now, as it is a little too large....

**Comment by Nailington** [comment]
You have to hope you get lucky on the runner you use

**Comment by YesterMester** [comment]
> Please rename the repo to `gba-host`
> 
> We have everything relatively linked assuming that name....

okay Ill do that and try and build again

**Comment by YesterMester** [comment]
i am currently trying a different workflow and so far so good.

**Comment by YesterMester** [comment]
I changed it to hugo workflow and it deployed

**Comment by YesterMester** [comment]
how do I link the fork with gba 2.0?

**Comment by Cattn** [comment]
> how do I link the fork with gba 2.0?
Well if your GBA 2.0 deployment is on the root of your repository, it'll just work

If it isn't, it should still work in theory, but I haven't extensively tested the system so I would have to ensure it does properly


If you are using a custom domain, make sure gba-host is reachable at yourdomain.tld/gba-host/

**Comment by Cattn** [comment]
It seems in your case the repo isn't deploying to the domain, so please setup your domain on that repo so it'll deploy/be visible from it

**Comment by Nailington** [comment]
@YesterMester May I ask what the URL of the site you are making is? And how is it deployed? Are you using GH-Pages or something else?

**Comment by YesterMester** [comment]
Securityubg.mooo.com I'm using a free subdomain and a modified fork of your guys and another users website. The only reason I've modified it is to get it to work with school/work blocking software.

**Comment by YesterMester** [comment]
I am using GitHub pages

**Comment by Nailington** [comment]
What repo is it pulling off of on your account? Can you link to it?

**Comment by Nailington** [comment]
I looked at your GH profile and found it! https://github.com/YesterMester/YexBU 

The way you are creating your domain link has issues with how it would normally be setup. I recommend instead renaming the repo to be `YesterMester.github.io` which should make all repos deploy with your custom domain.

I also recommend for other reasons to actually fork our repos, so that you can sync them easier!

**Comment by YesterMester** [comment]
YesterMester/YexBU

**Comment by YesterMester** [comment]
> I looked at your GH profile and found it! https://github.com/YesterMester/YexBU 
> 
> The way you are creating your domain link has issues with how it would normally be setup. I recommend instead renaming the repo to be `YesterMester.github.io` which should make all repos deploy with your custom domain.
> 
> I also recommend for other reasons to actually fork our repos, so that you can sync them easier! Not needed tho tbh

I can't do that as most schools including my own blocks GitHub links.

**Comment by Nailington** [comment]
> > I looked at your GH profile and found it! https://github.com/YesterMester/YexBU
> > The way you are creating your domain link has issues with how it would normally be setup. I recommend instead renaming the repo to be `YesterMester.github.io` which should make all repos deploy with your custom domain.
> > I also recommend for other reasons to actually fork our repos, so that you can sync them easier! Not needed tho tbh
> 
> I can't do that as most schools including my own blocks GitHub links.

Doing this with the CNAME should allow the existing behavior to continue! Take for example: https://nailington.github.io or https://math-study-dev.github.io Notice how they redirect? If you go direct to https://mathstudy.tech or https://mathstudy.dev (respective order) it has no way to block via the `github.io` filter

**Comment by Nailington** [comment]
Though I don't do the CNAME thing generally I don't think.... I normally just use the dedicated section in the repo settings on GH

**Comment by YesterMester** [comment]
How should I format the CNAME I at the moment can't change it back to YesterMester.github.io because of my school block filters.

**Comment by YesterMester** [comment]
The GitHub.io link is entirely blocked so is GitHub.com

**Comment by YesterMester** [comment]
I work on this in free time at home

**Comment by Nailington** [comment]
Hmm Let me look at my repo setup rq

**Comment by YesterMester** [comment]
I'm making this difficult I'm sorry about it. Would there be away to change a any files for GBA2.0 or GBA-host to get it working without changing my CNAME

**Comment by Nailington** [comment]
Found this!
![image](https://github.com/Cattn/GBA2.0/assets/111466491/5d287068-87bb-4361-b9c7-62d3a42806cd)
And yes I have a CNAME as well lol, it must have autogenerated.

**Comment by Nailington** [comment]
![image](https://github.com/Cattn/GBA2.0/assets/111466491/d3b127b6-fc3d-4145-bc14-de25b2793daa)

**Comment by Nailington** [comment]
So if you rename the repo (trust the process), change this setting, keep the CNAME, and deploy. Not only should this repo stay the same Domain wise, but every other repo SHOULD also fall under this domain as well by default.

If you for some reason wish against your entire account being tied to the domain, you can always create an Organization, and deploy it on the Org using the same method (`orgName.github.io`)

**Comment by YesterMester** [comment]
Yes I can do that but on my schools network it blocks all of GitHub so I use a free sub domain I currently have 4. ![Screenshot_20230927-181129.png](https://github.com/Cattn/GBA2.0/assets/74939964/d515eb0c-431e-4499-9249-b31c326ae78f)

**Comment by Nailington** [comment]
So add that in the box in settings, deploy, and it will be at that domain. I can confirm that it won't look at the github.io part. It is just so Github knows what the repo is for

**Comment by YesterMester** [comment]
I'll do what you said and see if it's unblocked for my end and get back.

**Comment by YesterMester** [comment]
Should it look like this?![PXL_20230927_221741447.MP.jpg](https://github.com/Cattn/GBA2.0/assets/74939964/5e7628ac-4eae-426e-8089-11b95877b886)

**Comment by Nailington** [comment]
Nope, u need to rename the repo first
Then fill in the box, make sure it agrees that it is vaild, then redeploy (edit README.md or smth)
IT SHOULD work

**Comment by Nailington** [comment]
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

You can read more there btw

**Comment by YesterMester** [comment]
I renamed the repo to GBA2.0 Then made securityubg.mooo.com again.

**Comment by Nailington** [comment]
Myb, should be named `yestermester.github.io`

**Comment by YesterMester** [comment]
Done.

**Comment by YesterMester** [comment]
Let me check if the website is blocked.

**Comment by YesterMester** [comment]
![PXL_20230927_223342939~2.jpg](https://github.com/Cattn/GBA2.0/assets/74939964/46a578f2-5ef2-4059-9ede-2d6e2b5a7c10)

**Comment by YesterMester** [comment]
> Myb, should be named `yestermester.github.io`
> 

Wait the repo or the pages? I'm so slow.

**Comment by Nailington** [comment]
repo itself should be renamed
then deploy, then navigate to the CNAME domain name (the mooooo one)

**Comment by YesterMester** [comment]
Omg. I'm so sorry

**Comment by Nailington** [comment]
No worry, you are some of the best to make it to the GH Issues land in a while. You communicate and have a brain lmao

**Comment by YesterMester** [comment]
Okay that's done should this be fixed? My network issue.

**Comment by YesterMester** [comment]
![PXL_20230927_223946457.jpg](https://github.com/Cattn/GBA2.0/assets/74939964/ef8df78b-ddb2-4c04-9ab2-28dfe859537d)

![PXL_20230927_223956803.jpg](https://github.com/Cattn/GBA2.0/assets/74939964/427ff3ef-8d2f-48eb-ad3d-b42ec3a672aa)

**Comment by Nailington** [comment]
Should be good

**Comment by YesterMester** [comment]
Oh no

![PXL_20230927_224212909.jpg](https://github.com/Cattn/GBA2.0/assets/74939964/001e7995-8619-4b8d-be28-297531661f58)

**Comment by YesterMester** [comment]
Same issues.

**Comment by YesterMester** [comment]
Is there something I'm missing?

**Comment by YesterMester** [comment]
It works in legacy fine! The only one that's not working is N64!

**Comment by YesterMester** [comment]
I figured it out thanks so much!

**Comment by Cattn** [comment]
> It works in legacy fine! The only one that's not working is N64!

To fix N64 just deploy Cattn/N64-host same way you did with gba-host

**Comment by Nailington** [comment]
> It works in legacy fine! The only one that's not working is N64!

Yea thats a seperate fork.... https://github.com/cattn/n64-host
